/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApprovalActionGroup: typeof import('./src/components/mining/ApprovalActionGroup.vue')['default']
    BarkxPoolNotice: typeof import('./src/components/mining/BarkxPoolNotice.vue')['default']
    CollapsibleCard: typeof import('./src/components/mining/CollapsibleCard.vue')['default']
    MiningShell: typeof import('./src/components/mining/MiningShell.vue')['default']
    PendingCornerNotice: typeof import('./src/components/mining/PendingCornerNotice.vue')['default']
    PoolStatusCard: typeof import('./src/components/mining/PoolStatusCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwapOptionsPanel: typeof import('./src/components/mining/SwapOptionsPanel.vue')['default']
  }
}
